# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: 192.168.1.1
    port: 54321
server:
  bind:
    host: 192.168.1.1
    port: 54321
catnip:
  my_ipv4_addr: 192.168.1.1
dpdk:
#  eal_init: ["-l", "0-3", "-n", "1", "-w", "aa89:00:02.0", "--vdev=net_vdev_netvsc0,iface=eth1"]
  eal_init: ["-c", "0xff", "-n", "4", "-w", "03:00.1","--proc-type=auto"]
#spdk:
#  transport: "PCIe"
#  devAddr: ""
#  namespace: 1
lwip:
  known_hosts:
    "24:8a:07:50:95:08": 192.168.1.1
    "50:6b:4b:48:f8:f2": 192.168.1.2
    "9c:dc:71:5d:41:e1": 10.10.1.5
    "9c:dc:71:49:b8:f1": 10.10.1.7
    "9c:dc:71:5c:8f:e1": 10.10.1.3
    "9c:dc:71:5b:22:71": 10.10.1.2
    "9c:dc:71:5d:41:f1": 10.10.1.6
    "9c:dc:71:5b:42:81": 10.10.1.4
    "9c:dc:71:5c:ef:b1": 10.10.1.1
    "9c:dc:71:5d:90:41": 10.10.1.8

# vim: set tabstop=2 shiftwidth=2
