# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
  connect_to:
    host: 192.168.1.1
    port: 54321
server:
  bind:
    host: 192.168.1.1
    port: 54321
catnip:
  my_ipv4_addr: 192.168.1.1
dpdk:
#  eal_init: ["-l", "0-3", "-n", "1", "-w", "aa89:00:02.0", "--vdev=net_vdev_netvsc0,iface=eth1"]
  eal_init: ["-c", "0xff", "-n", "4", "-w", "03:00.1","--proc-type=auto"]

# vim: set tabstop=2 shiftwidth=2
