# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
    connect_to:
        host: 198.19.200.1
        port: 6789
server:
    bind:
        host: 198.19.200.1
        port: 6789
    dpdk:
        eal_init: ["-c", "0x3fe",
                    "-n", "4",
                    "-w", "37:00.0",
                    "-b", "5d:00.0",
                    "--proc-type=auto",
                    "--master-lcore=1"]
    known_hosts:
        "b8:83:03:79:af:50": 198.19.200.2

# vim: set tabstop=2 shiftwidth=2
#  eal_init: ["-l", "0-3", "-n", "1", "-w", "aa89:00:02.0", "--vdev=net_vdev_netvsc0,iface=eth1"]
#0x3fe is for the first 10 cores (excluding core 0)
