# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

client:
    connect_to:
        host: 198.19.200.1
        port: 6789
server:
    bind:
        host: 198.19.200.1
        port: 6789
dpdk:
    eal_init: ["-c", "0xe",
        "-n", "1",
        "-w", "17:00.1",
        "--file-prefix", "dpdk_iped"]
    known_hosts:
        "b8:59:9f:b4:41:15": 192.168.1.10
        "b8:59:9f:b4:41:9d": 192.168.1.11

# vim: set tabstop=2 shiftwidth=2
#  eal_init: ["-l", "0-3", "-n", "1", "-w", "aa89:00:02.0", "--vdev=net_vdev_netvsc0,iface=eth1"]
#0x3fe is for the first 10 cores (excluding core 0)
#"--proc-type=auto",
#"--master-lcore=1"]
