[package]
name = "catnip_libos"
version = "0.1.0"
authors = ["Sujay Jayakar <sujayakar314@gmai.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
catnip = { path = "../catnip" }
libc = "0.2.77"
clap = "2.33.3"
yaml-rust = "0.4.4"
anyhow = "1.0.32"
hashbrown = { version = "0.9", features = ["nightly"] }
bytes = "0.5.6"
futures = "0.3"
rand = { version = "0.7.3", features = ["small_rng"] }

[build-dependencies]
bindgen = "0.55.1"
