[package]
name = "catnip"
version = "0.1.0"
authors = ["Michael Lowell Roberts <mirobert@microsoft.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "staticlib"]

[dependencies]
byteorder = "1.3.1"
crc = "1.8.1"
custom_error = "1.6.0"
derive_more = "0.15.0"
either = "1.5"
eui48 = "0.4.6"
float_duration = "0.3.3"
lazy_static = "1.3.0"
libc = "0.2.62"
log = "0.4"
maplit = "1.0.1"
nom = "5.0.0"
num-derive = "0.2.5"
num-traits = "0.2.7"
#parking_lot = "0.9"
rand = "0.6.5"
rand_chacha = "0.1.1"
rand_core = "0.4.0"
serde = "1.0.91"
serde_yaml = "0.8.9"
spin = "0.5.0"

[dev-dependencies]
flexi_logger = { version = "0.13.2", features = ["colors"] }
