[package]
name = "qip"
version = "0.1.0"
authors = ["Michael Lowell Roberts <mirobert@microsoft.com>"]
edition = "2018"

[dependencies]
custom_error = "1.6.0"
eui48 = "0.4.6"
lazy_static = "1.3.0"
rand_chacha = "0.1.1"
rand_core = "0.4.0"
spin = "0.5.0"
derive_more = "0.14.0"
byteorder = "1.3.1"
num-traits = "0.2.7"
num-derive = "0.2.5"
serde_yaml = "0.8.9"
serde = "1.0.91"
float_duration = "0.3.3"
log = "0.4"

[dev-dependencies]
flexi_logger = { version = "0.13.2", features = ["colors"] }
