client:
  connect_to:
    host: 10.10.1.5
    port: 54321
server:
  bind:
    host: 10.10.1.5
    port: 54321
dpdk:
#  eal_init: ["-l", "0-3", "-n", "1", "-w", "aa89:00:02.0", "--vdev=net_vdev_netvsc0,iface=eth1"]
  eal_init: ["-c", "0xff", "-n", "4", "-w", "03:00.1","--proc-type=auto"]
  host: 10.10.1.2
# vim: set tabstop=2 shiftwidth=2
